# NumPy Notebook

In [2]:
list = [1,2,3,4]

In [4]:
import numpy as np
arr = np.array(list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
my_mat = [[1,2,3],[4,5,6],[6,7,8]]

In [7]:
mat = np.array(my_mat)

In [8]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
# Linspace will take third argument as a number of points we want
# Arange will take third argument as a step size we want

In [21]:
np.eye(4)  #This will create an identity matrix of 4*4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.74019817, 0.22250746, 0.65619248, 0.58512761, 0.95430271])

In [23]:
np.random.rand(5,5)

array([[0.90220863, 0.13841608, 0.05964333, 0.78859897, 0.40017973],
       [0.45571388, 0.74853083, 0.2157242 , 0.09728557, 0.23271037],
       [0.84799128, 0.94380348, 0.82455813, 0.69466315, 0.47457255],
       [0.23813292, 0.74101758, 0.44685631, 0.64670408, 0.57992893],
       [0.25339766, 0.36619071, 0.44243406, 0.52776328, 0.16292157]])

In [24]:
np.random.randn(2)

array([-0.78404029,  0.31081061])

In [25]:
np.random.randn(4,4)

array([[-0.77889788,  0.17469612,  0.88038883, -1.57935705],
       [-0.28278281, -1.01866887, -0.3304862 , -0.072069  ],
       [-0.09475205,  0.76913835, -0.09592055,  1.71276146],
       [ 1.35480725,  1.74453034,  0.56056788,  0.70996752]])

In [27]:
np.random.randint(1,100)

73

In [28]:
np.random.randint(1,100,5)

array([39, 57,  9, 53, 43])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([19, 25, 24, 43, 25, 22, 15, 49, 17, 18])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

49

In [42]:
ranarr.argmax()

7

In [43]:
ranarr.min()

15

In [44]:
ranarr.argmin()

6

In [45]:
arr  = arr.reshape(5,5)

In [46]:
ranarr.dtype

dtype('int32')

In [47]:
arr2 = np.arange(0,11)

In [48]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr2[8]

8

In [52]:
arr2[1:5]

array([1, 2, 3, 4])

In [53]:
arr2[:6]

array([0, 1, 2, 3, 4, 5])

In [54]:
arr2[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr2[0:5] = 100 # Broadcasting

In [56]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr2 = np.arange(0,11)

In [58]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
slice_of_arr2 = arr2[0:6]

In [60]:
slice_of_arr2

array([0, 1, 2, 3, 4, 5])

In [61]:
slice_of_arr2[:] = 99

In [62]:
slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [63]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
arr2_copy = arr2.copy()

In [65]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr2_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr2_copy[:] = 100

In [68]:
arr2_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [69]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [2]:
import numpy as np
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
# 2d arrays are essentially matrices

In [5]:
arr_2d[0][0]

5

In [6]:
arr_2d[0]

array([ 5, 10, 15])

In [7]:
arr_2d[1][1]

25

In [8]:
arr_2d[1,2]

30

In [9]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [10]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [11]:
arr = np.arange(1,11)

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
bool_arr = arr > 5

In [15]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [16]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [18]:
arr[arr<3]

array([1, 2])

In [19]:
arr_2d = np.arange(50).reshape(5,10)

In [20]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [22]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [23]:
## Numpy operations

In [24]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [30]:
arr / arr

<ipython-input-30-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [31]:
1/arr

<ipython-input-31-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [32]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [33]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [34]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [35]:
np.max(arr)

10

In [36]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [37]:
np.log(arr)

<ipython-input-37-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [39]:
np.ones(5) * 5

array([5., 5., 5., 5., 5.])

In [40]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [47]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [48]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [50]:
mat[3:4,4:]

array([[20]])

In [51]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [52]:
mat[4]

array([21, 22, 23, 24, 25])

In [53]:
mat.sum()

325

In [54]:
mat.std()

7.211102550927978

In [55]:
mat.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325],
      dtype=int32)

In [1]:
import numpy as np

In [3]:

for i==3:
    print

AttributeError: 'numpy.ndarray' object has no attribute 'arange'